### PR TITLE
Disable custom inspect implementations

### PR DESCRIPTION
**Pull request by dividedmind**
This is unfortunate, but some objects can have custom inspects that are broken; for example, PrismaClient hangs if one tries
to inspect before the database is connected. There is no way to know upfront whether a particular implementation is broken
or not.

Fixes https://github.com/getappmap/appmap-node/issues/75

### CODE REVIEW

**Comment by kgilpin** [comment]
Should we have a way for users to whitelist their implementations?

**Comment by dividedmind** [comment]
> Should we have a way for users to whitelist their implementations?

I did give it some thought, but I came to the conclusion it's not worth the added complexity, at least at the moment; the whitelisting also wouldn't work if the object is not toplevel in value but eg. in an array or a property. If there is user demand we can revisit, but it probably would have take the form of a different method than `inspect.custom` so AppMap whitelisting is explicit.

**Comment by kgilpin** [comment]
Maybe a label in the code itself would be a good way to implement white listing.

**Review by kgilpin — APPROVED** [review]

**Comment by dividedmind** [comment]
> Maybe a label in the code itself would be a good way to implement white listing.

A function with a specific name would be more idiomatic, I think.

**Review by zermelo-wisen — APPROVED** [review]

**Pull request merged**
