### PR TITLE
Instrument named lambdas

### PR DESCRIPTION
**Pull request by dividedmind**
This change makes appmap-node instrument exported lambdas of the forms:
```javascript
export const esmLambda = () => {};
exports.cjsLambda = () => {};
const lambda = () => {};
exports.lambda = lambda;
```

(Note this was partly an effort to improve mapping of https://github.com/mohamedsamara/mern-ecommerce — cf. #107 — although it really didn't make much difference there due to how that projects uses almost no named functions. @kgilpin this change makes the handlers in our cli instrumented — although without full async tracking (#103) the AppMaps are still misleading.)

### CODE REVIEW

**Comment by kgilpin** [comment]
@dividedmind how can I test this on a project like the CLI without merging and releasing it first?

**Comment by dustinbyrne** [comment]
I've been using `yarn link -A ~/dev/getappmap/appmap-node`, adding `appmap-node` as a dev dependency, then `yarn appmap-node $COMMAND`

**Comment by dustinbyrne** [comment]
I tried this in a Nest project and it didn't capture the arrow function. Maybe I'm missing something?

```ts
import { Controller, Get } from '@nestjs/common';
import { RequireUser } from '../auth/require-user.decorator';
import { User } from '../users/users.model';

@Controller('hello')
export class HelloController {
  @Get()
  sayHello(@RequireUser() user: User): string {
    const generateGreeting = () => `Hello ${user.login}!`;
    return generateGreeting();
  }
}
```

image

There's no reference to `generateGreeting` in the JSON either.

**Comment by dustinbyrne** [comment]
I was able to record that function call only by exporting it. Is this expected?

E.g.:
```ts
import { Controller, Get } from '@nestjs/common';
import { RequireUser } from '../auth/require-user.decorator';
import { User } from '../users/users.model';
import { generateGreeting } from './generateGreeting';

@Controller('hello')
export class HelloController {
  @Get()
  sayHello(@RequireUser() user: User): string {
    return generateGreeting(user.login);
  }
}
```

**Comment by dividedmind** [comment]
> I was able to record that function call only by exporting it. Is this expected?
> 
> E.g.:
> 
> ```ts
> import { Controller, Get } from '@nestjs/common';
> import { RequireUser } from '../auth/require-user.decorator';
> import { User } from '../users/users.model';
> import { generateGreeting } from './generateGreeting';
> 
> @Controller('hello')
> export class HelloController {
>   @Get()
>   sayHello(@RequireUser() user: User): string {
>     return generateGreeting(user.login);
>   }
> }
> ```

Yes, only exported lambdas are instrumented. Instrumenting all lambdas is definitely possible (just one line change in fact) but it leads to an awful AppMap bloat... I've been thinking, maybe we could allow configuring or marking additional lambdas to be instrumented, but I don't think instrumenting all of them is a good idea. Local lambdas are mostly local utilities.

**Comment by dividedmind** [comment]
> I've been using `yarn link -A ~/dev/getappmap/appmap-node`, adding `appmap-node` as a dev dependency, then `yarn appmap-node $COMMAND`

You can also `yarn prepack` in the `appmap-node` directory and then use `<appmap-node>/bin/appmap-node.js` as the command (I use an alias).

**Comment by kgilpin** [comment]
Are there still a lot of you only record the names ones?

**Comment by dividedmind** [comment]
> Are there still a lot if you only record the names ones?

That's my experience... if you want to try it out, here's a patch:
```patch
diff --git a/src/hooks/instrument.ts b/src/hooks/instrument.ts
index d02ec45..5e6f8fa 100644
--- a/src/hooks/instrument.ts
+++ b/src/hooks/instrument.ts
@@ -97,14 +97,6 @@ export function transform(program: ESTree.Program, sourceMap?: SourceMapConsumer
           if (pkg?.exclude?.includes(id.name)) return;
           assert(declarator.init === fun);
 
-          if (container.type === "Program") {
-            // note: the type is checked by the assert above
-            topLevelConstLambdas.set(id.name, declarator as NamedLambda);
-            return;
-          }
-
-          if (container.type !== "ExportNamedDeclaration") return;
-
           debug(`Instrumenting ${id.name}`);
           declarator.init = wrapLambda(
             fun,
```

**Comment by dustinbyrne** [comment]
I've spent some time thinking about it and ultimately I think these two functions should be treated equally, by default.
```ts
function func() {}
const arrowFunc = () => {};

func();
arrowFunc();
```

Is it maybe something that could be configured?

**Comment by kgilpin** [comment]
I agree with @dustinbyrne that I don't think these two syntaxes differ much in a developer's mind, they are both named functions.

**Comment by dustinbyrne** [comment]
> Yes, only exported lambdas are instrumented. Instrumenting all lambdas is definitely possible (just one line change in fact) but it leads to an awful AppMap bloat... I've been thinking, maybe we could allow configuring or marking additional lambdas to be instrumented, but I don't think instrumenting all of them is a good idea. Local lambdas are mostly local utilities.

We'll have to find some kind of balance here. In a case where you're receiving an asynchronous callback I think it might make more sense to have the callback recorded, even if it's an anonymous function, to aggregate the calls within under a common ancestor. Imagine a case where an event emitter outlives the scope where its listeners are bound.

```ts
const emitter = new EventEmitter();

function bindListeners() {
  emitter.on("example", (e) => {
    const err = validateEvent(e);
    if (err) {
      console.error(err);
      return;
    }

    handleEvent(e);
  });
}

emitter.emit("example", "test");
```

**Comment by dividedmind** [comment]
> I agree with @dustinbyrne that I don't think these two syntaxes differ much in a developer's mind, they are both named functions.

What about
```javascript
function doStuff(xs) {
  const process = (x) => x * 2;
  return xs.map(process);
}```
— should `process` be recorded?

**Comment by kgilpin** [comment]
Speaking as someone who does that a lot, I'd say yes.

**Comment by dividedmind** [comment]
@kgilpin @dustinbyrne do you mind taking a look?

**Review by dustinbyrne — APPROVED** [review]

**Pull request merged**
