### PR TITLE
Fixes for dots in paths and relative paths

### LINKED ISSUE #100: Use root-relative paths in AppMaps

### LINKED ISSUE #104: Package recorded with no `name`
This data was captured from https://github.com/getappmap/appmap-services/tree/feat/speak-api with a default appmap.yml

```yaml
name: api-service
appmap_dir: tmp/appmap
packages:
  - path: .
    exclude:
      - node_modules
      - .yarn
```

See the example AppMap attached.

[2024-01-25T20:17:31.404Z_-v1-ai-speak.appmap.zip](https://github.com/getappmap/appmap-node/files/14057497/2024-01-25T20.17.31.404Z_-v1-ai-speak.appmap.zip)

### PR DESCRIPTION
**Pull request by dividedmind**
Fixes #104
Fixes #100 

@dustinbyrne could you please verify this fixes your issues?

### CODE REVIEW

**Review by dustinbyrne — CHANGES_REQUESTED** [review]
It's close, but I'm still getting relative paths in some cases. See the package names and path displayed in the attached image.
image

Including the AppMap here as well.
[2024-02-02T19:36:03.267Z_-v1-ai-speak.appmap.zip](https://github.com/getappmap/appmap-node/files/14144697/2024-02-02T19.36.03.267Z_-v1-ai-speak.appmap.zip)

**Comment by dividedmind** [comment]
> It's close, but I'm still getting relative paths in some cases. See the package names and path displayed in the attached image. image
> 
> Including the AppMap here as well. [2024-02-02T19:36:03.267Z_-v1-ai-speak.appmap.zip](https://github.com/getappmap/appmap-node/files/14144697/2024-02-02T19.36.03.267Z_-v1-ai-speak.appmap.zip)

I'm going to need some help to reproduce this.

**Comment by dustinbyrne** [comment]
Here's a basic reproduction of the issue. See the README for running instructions.
https://github.com/dustinbyrne/appmap-node-108-repl

**Comment by dividedmind** [comment]
@dustinbyrne should work now, can you take a look? thanks!

**Review by dustinbyrne — APPROVED** [review]
Looks good!

**Pull request merged**
