### PR TITLE
Support Jest test recordings

### PR DESCRIPTION
**Pull request by dividedmind**
Also, some refactoring and UX improvements.

Install:
```console
$ yarn pack --install-if-needed
$ npm install --global package.tgz
```

Then in some project, for example:
```console
$ appmap-node yarn jest
```

### CODE REVIEW

**Comment by kgilpin** [comment]
404 files - are some accidental?

**Comment by kgilpin** [comment]
Can there be a description of how to try this?

**Comment by dividedmind** [comment]
> 404 files - are some accidental?

No. I decided to give a try to yarn feature of [in-repo caching of dependencies](https://yarnpkg.com/features/caching#offline-mirror). This allows much faster installs (nothing extra to download) and resilience in face of random npmjs failures.

**Comment by dividedmind** [comment]
> Can there be a description of how to try this?

It's right there in the readme :)

**Review by dustinbyrne — APPROVED** [review]

**Pull request merged**
